name: Delete Image using pi-gen
run-name: Delete Image ${{ github.event.inputs.version }}
 
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version / Tag (vx.x.x):'     
        required: true

jobs:
  setup_environment:
    runs-on: [ubuntu-latest] 
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: ${{ github.event.inputs.version }}
        draft: true
        prerelease: true

  build_images:
    name: Build Raspbian Homebridge Image ${{ matrix.pi-gen-version }}
    needs: setup_environment
    runs-on: [ubuntu-latest] 
    strategy:
      fail-fast: false
      matrix:
        pi-gen-version: [
          master,
          arm64
        ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'release-candidate'

      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          pi-gen-version: ${{ matrix.pi-gen-version }}
          image-name: "Homebridge"
          release: bullseye
#         IMG_DATE="Raspbian"
          hostname: "homebridge"
          enable-ssh: 1
          stage-list: stage0 stage1 stage2 stage3_homebridge
          username: pi
          disable-first-boot-user-rename: 1
#         FIRST_USER_PASS="raspberry"

      - name: Calculate Checksum
        id: get_sha256_checksum
        run: |
          export IMAGE_SHA256_CHECKSUM=$(shasum -a 256 deploy/image_Raspbian-Homebridge.zip | awk '{print $1}')
          echo "$IMAGE_SHA256_CHECKSUM deploy/image_Raspbian-Homebridge.zip"
          echo ::set-output name=IMAGE_SHA256_CHECKSUM::${IMAGE_SHA256_CHECKSUM}

      - name: Generate rpi-image-repo.json 
        id: generate_rpi-image-repo
        run: |
          sudo RPI_IMAGER_NAME="Homebridge" RPI_IMAGER_DESCRIPTION="Official Homebridge Raspberry Pi Image" RPI_IMAGER_ICON="https://user-images.githubusercontent.com/3979615/116509191-3c35f880-a906-11eb-9a7f-7cad7c2aa641.png" RPI_IMAGER_WEBSITE="https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started" ./make_rpi-imager-snipplet.py -u"https://github.com/homebridge/homebridge-raspbian-image/releases/download/${{ github.event.inputs.version }}/Raspbian-Homebridge-${{ github.event.inputs.version }}.zip"

      - uses: actions/upload-artifact@v3
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}

      - name: Upload Image
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: deploy/image_Raspbian-Homebridge.zip
          asset_name: Raspbian-Homebridge-${{ github.event.inputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload rpi-image-repo.json
        id: upload-rpi-image-repo-json 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: deploy/rpi-image-repo.json
          asset_name: rpi-image-repo.json
          asset_content_type: application/json

  finalize_build:
      name: Finalize ${{ github.event.inputs.version }}
      needs: setup_environment
      runs-on: [ubuntu-latest]
      steps:
        
      - name: Upload rpi-image-repo.json
        id: upload-rpi-image-repo-json 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: deploy/rpi-image-repo.json
          asset_name: rpi-image-repo.json
          asset_content_type: application/json

